a = input("Type something: ")
print("The primitive type of this value is ", type(a))
print("Only spaces? ", a.isspace())
print("Is it a number? ", a.isnumeric())
print("Is it alphabetic? ", a.isalpha())
print("Is it alphanumeric? ", a.isalnum())
print("Has uppercase letters? ", a.isupper())
print("Has lowercase letters? ", a.islower())
print("Is it capitalized? ", a.istitle())
